### ISSUE TITLE
Boxplot rendering in jupyterlab - highcharts-more issue?

### ISSUE THREAD

**Issue by priyankshah7** [highcharts-for-python/highcharts-core#114]
**Describe the bug**
There seems to be an issue when attempting to display a boxplot chart in jupyterlab. Having had a look at the codebase, it seems like `highcharts-more` should be included but for some reason doesn't seem like it is. This hasn't been an issue with any other charts tested so far (line, bar, scatter).

![image](https://github.com/highcharts-for-python/highcharts-core/assets/20361781/bc0f6c94-1e6e-4032-a06e-d56feb1724d2)

![image](https://github.com/highcharts-for-python/highcharts-core/assets/20361781/41976ef2-4eba-490a-8f2a-7e6180e6ae5c)

**To Reproduce**
Attempt to render a boxplot chart in jupyterlab using the `.display()` method.

**Your Environment:**
 - OS: Windows
 - Python Version: 3.11

**Comment by hcpchris** [comment]
Hi @priyankshah7 : Hmm - which version of **Highcharts Core for Python** are you using? 

This looks to be an issue that was resolved in #12 as of v.1.2.0 (and then further enhanced in #78 as of v.1.3.0). It also seems to be passing tests now when I check it locally (FWIW, I tested both using ``options.plot_options.boxplot.BoxPlotOptions`` and ``options.series.boxplot.BoxPlotSeries`` and everything included ``highcharts-more`` as expected)

If you are running an earlier version of **Highcharts Core for Python**, I'd recommend upgrading to the latest version with ``pip install --upgrade highcharts-core``. And if you are already using the latest version, can you share some pseudo-code (or actual code) to help me reproduce the issue to diagnose what might be happening? If you'd prefer to do that privately / not in a public issue, you can email support@highchartspython.com

And finally, since you mention you were using ``.display()`` to render things in a Jupyter context, can you let me know if you were displaying other charts in the same notebook *before* trying to render the Boxplot? I have a theory that the JS we're using to dynamically load the scripts for multiple charts may be conflicting when applied to multiple charts within the same view, but that's pure speculation at this stage so it may be helpful as a data point to aid in diagnostics.

**Comment by priyankshah7** [comment]
I'm using `highcharts-core==1.3.7`. Here's a minimum example which fails locally for me:

```python
from highcharts_core.chart import Chart
from highcharts_core.options import HighchartsOptions
from highcharts_core.options.plot_options import PlotOptions
from highcharts_core.options.axes.x_axis import XAxis
from highcharts_core.options.axes.y_axis import YAxis
from highcharts_core.options.axes.title import AxisTitle
from highcharts_core.options.title import Title
from highcharts_core.options.legend import Legend
from highcharts_core.options.plot_options.series import SeriesOptions
from highcharts_core.options.series.labels import SeriesLabel
from highcharts_core.options.credits import Credits

from highcharts_core.options.series.boxplot import BoxPlotSeries

chart_options = HighchartsOptions(
    title=Title(
        text="Historic World Population by Region", align="center"
    ),
    y_axis=YAxis(title=AxisTitle(text="Number of Employees")),
    x_axis=XAxis(title=AxisTitle(text="Year"), categories=["Africa", "America", "Asia", "Europe", "Oceania"]),
    legend=Legend(layout="vertical", align="right", vertical_align="middle"),
    plot_options=PlotOptions(
        series=SeriesOptions(
            point_start=2010, label=SeriesLabel(connector_allowed=False)
        )
    ),
    caption=None,
    credits=Credits(enabled=False),
    inverted=True
)

series = {
    "name": 'Observations',
    "data": [
        [760, 801, 848, 895, 965],
        [733, 853, 939, 980, 1080],
        [714, 762, 817, 870, 918],
        [724, 802, 806, 871, 950],
        [834, 836, 864, 882, 910]
    ],
}

chart_options.add_series(BoxPlotSeries(**series))

boxplotchart = Chart.from_options(chart_options)
boxplotchart.display()
```

There were additional charts in my original attempt but I've removed the others to only include the boxplot chart and still faced with the same issue. Also tried rerunning on a completely separate jupyterlab instance which hasn't helped. I don't think it should make a difference but I'm using the latest jupyterlab release (4.0.6).

Here's a slightly more detailed error message from the logs:
![image](https://github.com/highcharts-for-python/highcharts-core/assets/20361781/e9c2f160-eb35-44c0-b0c0-1b06a6b981de)

**Comment by hcpchris** [comment]
Thanks, @priyankshah7 ! Let me see if I can recreate this issue on my end. One other request - it in general is highly unlikely to be at the root cause of this, but just to be on the safe side - can you share with me a list of the Python modules/libraries you have in your environment? The output of ``pip list`` would be great. That way I can basically recreate your environment exactly, as that may be helpful in recreating and subsequently diagnosing what may be causing this bug.

**Comment by priyankshah7** [comment]
Hey @hcpchris, sure here it is:

Package                   Version
------------------------- ------------
anyio                     4.0.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.0
async-lru                 2.0.4
attrs                     23.1.0
Babel                     2.12.1
backcall                  0.2.0
beautifulsoup4            4.12.2
bleach                    6.0.0
certifi                   2023.7.22
cffi                      1.16.0
charset-normalizer        3.3.0
colorama                  0.4.6
comm                      0.1.4
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
esprima                   4.0.1
executing                 2.0.0
fastjsonschema            2.18.1
fqdn                      1.5.1
highcharts-core           1.3.7
idna                      3.4
ipykernel                 6.25.2
ipython                   8.16.1
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
jupyter_client            8.3.1
jupyter_core              5.3.2
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab                4.0.6
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.0
MarkupSafe                2.1.3
matplotlib-inline         0.1.6
mistune                   3.0.2
nbclient                  0.8.0
nbconvert                 7.8.0
nbformat                  5.9.2
nest-asyncio              1.5.8
notebook_shim             0.2.3
numpy                     1.26.0
overrides                 7.4.0
packaging                 23.2
pandas                    2.1.1
pandocfilters             1.5.0
parso                     0.8.3
pickleshare               0.7.5
pip                       23.2.1
platformdirs              3.10.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
psutil                    5.9.5
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.16.1
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.3.post1
pywin32                   306
pywinpty                  2.0.11
PyYAML                    6.0.1
pyzmq                     25.1.1
referencing               0.30.2
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.3
Send2Trash                1.8.2
setuptools                68.2.0
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.6.3
terminado                 0.17.1
tinycss2                  1.2.1
tornado                   6.3.3
traitlets                 5.10.1
types-python-dateutil     2.8.19.14
tzdata                    2023.3
uri-template              1.3.0
urllib3                   2.0.5
validator-collection      1.5.0
wcwidth                   0.2.8
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.3
wheel                     0.41.2

**Comment by hcpchris** [comment]
Thanks, @priyankshah7 ! I'm finalizing a new release today, but as soon as that is done (but before I actually do the release) I'll recreate the environment on my end and see if I can reproduce / diagnose what's happening here. If it's a bug I can reproduce / diagnose today, I'll try to incorporate a fix into today's release.

**Comment by hcpchris** [comment]
Hi @priyankshah7 : So I refactored the underlying code a little bit in v.1.4.0 (which was just released), and I am able to get boxplots to render properly. Can you upgrade to the latest version and give it a try? While I had some difficulty reproducing the original bug under v.1.3.7, the refactoring may have resolved some of the issues you were encountering. 

I'll leave this issue open for the time being to confirm whether it is still occurring.

**Comment by priyankshah7** [comment]
Hi @hcpchris - the update to v1.4.0 seems to have solved the issue!. Boxplot and AreaRange charts are now rendering (haven't tested others that depend on highcharts-more but presumably will have been the same issue). Thanks for fixing and happy to close the issue :)

**Comment by hcpchris** [comment]
Awesome - glad to hear it, and thanks for confirming!
